---
services:
  - class: org.jlab.rec.ec.ECReconstruction
    name: EC
  - class: org.jlab.rec.ftof.SCReconstruction
    name: FTOF
  - class: org.jlab.rec.dc.services.HitBasedTracking
    name: DCHB
  - class: org.jlab.rec.dc.services.TimeBasedTracking
    name: DCTB
  - class: org.jlab.rec.eb.CLASEventBuilder
    name: EB
